### ISSUE TITLE
Latest version of MOOG

### ISSUE THREAD

**Issue by jobovy** [andycasey/moog#7]
Hi Andy,

This installer works great, thanks! But is there any way to install a newer version of MOOG? There seems to be a more recent version here:

http://www.as.utexas.edu/~chris/moog.html

By the way: do you have / know of a python reader for MOOG output?

Thanks,

Jo

**Comment by DanielAndreasen** [comment]
Hi Jo,

For the first question I can not help. This is for Andy to do (but it could be nice with the latest version).
For the second question, which output do you need to read? From the synthesis or abundances?

I have worked a bit with both and have some small scripts that might be helpful for reading the output.

Cheers,
Daniel

**Comment by andycasey** [comment]
Hi Jo,

I will update this repository to the latest version of MOOG soon, but AFAIK there is not much that has changed between versions. The last major change that would affect science results was the 2013 version that includes proper scattering treatment at blue wavelengths.

I have a script that runs [MOOG as a context manager](https://github.com/andycasey/moog/blob/batch/moog.py) and parses the input/output for `abfind` and `synth` routines which might be helpful for you. It's pretty hacky.

I'm also writing a [code to analyse stellar spectra](https://github.com/andycasey/new-oracle) that performs synthesis on-the-fly. It uses a Python-wrapped-C-wrapped-Fortran butchered version of MOOG (the latest version, actually), so you don't need to deal with input/output files at all. This version is about 3-5x faster than standard MOOG, but there is no documentation yet. It can handle MARCS/Castelli Kurucz/Stagged <3D> models, but it's also pretty intertwined with the rest of the repository and there are [known issues/limitations](https://github.com/andycasey/new-oracle/issues).

I'll leave this issue open until I get time to update MOOG to the most recent release.

Andy

**Comment by jobovy** [comment]
Hi Daniel and Andy,

Thanks; good to know that nothing interesting has changed in the new version. I'm just trying to make sure I'm using the same MOOG as my collaborators are using (and directly installing MOOG failed for me).

I'm trying to run synth and read the output spectrum. Sounds like I should be able to do that with the context manager, so I will try that out later today. I'm aiming for something to include in my [apogee](https://github.com/jobovy/apogee) repository, to allow easy analysis of the APOGEE data, so something somewhat stable would be preferable. 

Thanks,

Jo

**Comment by andycasey** [comment]
In that case I would go with one of @DanielAndreasen's scripts or the context manager I linked. Feel free to email me if you run into MOOG oddities. There's a lot of undocumented knowledge!

**Comment by DanielAndreasen** [comment]
However, my scripts are not online and they are very hacky. The one I think about get the job done, on reading the output, plotting it with the line list for the synthetic spectra.
The code is poorly documented, but if you want it, just let me know, and I can send it.

**Comment by jobovy** [comment]
I'll try Andy's context manager first and if that doesn't work, maybe I'll
ask you for the scripts. The linelist I'm using has ~130k lines, so
overplotting that might not be good...

**Comment by jobovy** [comment]
Hi Andy,

I updated the moogsilent installation to use the JUL2014 release of MOOG in my 'batch' branch of your code jobovy/moog@497722ecef9f43bf44746c46549414817299ecca. I think I've done basically the same as you did before and the code seems to compile and run, but I will refrain from opening a pull request because I haven't updated master (and I've only tested this on a Mac). Potentially you could pull this in as a 'batchjul2014' branch of the installer.

Jo

**Comment by andycasey** [comment]
Done; this is now on the `batch.2014jul` branch of this repo. Thanks @jobovy (and for the polite in-person reminder)
