### ISSUE TITLE
Moog install issues on El Capitan?

### ISSUE THREAD

**Issue by MarkDurre** [andycasey/moog#9]
I'm getting problems installing moog on OS El Capitan. I attach error file. It seems to be something to do with wheel build and not having access to /private directory. I am aware of the new SIP under El Capitan and I have that disabled. I also have made sure I have full read/write permissions on /private/tmp. I don't have much experience on this sort of error, so any help appreciated.

[moog-install-errors.txt](https://github.com/andycasey/moog/files/1290219/moog-install-errors.txt)

**Comment by andycasey** [comment]
I haven't seen this error message before. It looks like MOOG itself cannot compile because of a library issue (not a python wrapper issue). Sorry, but I'm not sure how to start debugging this remotely.

**Comment by MarkDurre** [comment]
Issue is solved, using a Frameworks build of Python, rather than the one "out of the box" with Mac OS
